import type { Metadata } from "next";
import { Inter, League_Spartan } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const leagueSpartan = League_Spartan({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Supercoach Demo",
  description: "Generated by Sim",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={leagueSpartan.className}>{children}</body>
    </html>
  );
}
