// Mock Player Data
const mockData = [
    {
        name: 'Max Gawn',
        player_value: 432000,
        player_pos: 'RUC',
        team: 'Melbourne Demons',
        team_logo: '/images/team-logos/melb.svg',
        ownership: 24,
        break_even: 103,
        points: 197,
        id: 'mg-melb',
    },
    {
        name: 'Christian Petracca',
        player_value: 641900,
        player_pos: 'MID',
        team: 'Melbourne Demons',
        team_logo: '/images/team-logos/melb.svg',
        ownership: 43,
        break_even: 124,
        points: 113,
        id: 'cp-melb',
    },
    {
        name: 'Oscar McInerney',
        player_value: 522700,
        player_pos: 'RUC',
        team: 'Brisbane Lions',
        team_logo: '/images/team-logos/bl.svg',
        ownership: 0.68,
        break_even: 87,
        points: 108,
        id: 'om-bl',
    },
    {
        name: 'Jack Viney',
        player_value: 5225300,
        player_pos: 'MID',
        team: 'Melbourne Demons',
        team_logo: '/images/team-logos/melb.svg',
        ownership: 2,
        break_even: 137,
        points: 104,
        id: 'jv-melb',
    },
    {
        name: 'Will Ashcroft',
        player_value: 457500,
        player_pos: 'MID',
        team: 'Brisbane Lions',
        team_logo: '/images/team-logos/bl.svg',
        ownership: 19,
        break_even: 65,
        points: 102,
        id: 'wa-bl',
    },
    {
        name: 'Jake Bowey',
        player_value: 353700,
        player_pos: 'DEF',
        team: 'Melbourne Demons',
        team_logo: '/images/team-logos/melb.svg',
        ownership: 0.2,
        break_even: 72,
        points: 96,
        id: 'jb-melb',
    },
    {
        name: 'Hugh McCluggage',
        player_value: 547900,
        player_pos: 'MID',
        team: 'Brisbane Lions',
        team_logo: '/images/team-logos/bl.svg',
        ownership: 0.4,
        break_even: 19,
        points: 92,
        id: 'hmcm-bl',
    },
    {
        name: 'Jarryd Lyons',
        player_value: 365800,
        player_pos: 'MID',
        team: 'Brisbane Lions',
        team_logo: '/images/team-logos/bl.svg',
        ownership: 0.4,
        break_even: 55,
        points: 89,
        id: 'jl-bl',
    },
    {
        name: 'Harris Andrews',
        player_value: 495800,
        player_pos: 'DEF',
        team: 'Brisbane Lions',
        team_logo: '/images/team-logos/bl.svg',
        ownership: 3,
        break_even: 24,
        points: 87,
        id: 'ha-bl',
    },
    {
        name: 'Angus Brayshaw',
        player_value: 484300,
        player_pos: 'DEF/MID',
        team: 'Melbourne Demons',
        team_logo: '/images/team-logos/melb.svg',
        ownership: 6,
        break_even: 84,
        points: 83,
        id: 'ab-melb',
    },
];

export default mockData;